#+TITLE Personal Notes for 2016
#+AUTHOR Samuel Hibbard
#+DATE <2016-01-05 Tue>

* John 1:1-17
  - "That was the true Light, which lighteth every man that cometh into the world." 
    v. 9
    * Christ is the true light. I need to do everything that I can to show that light
      to my family. My wife and soon to be my newborn son. I feel that I need to pray
      and read better the scriptures in order to do this thing for Him and my wife. 
      I want to be a worthy priesthood holder since He will be gaining that soon.
  - My Goals for this year:
    * Pray morning and night on my knees
    * Make at least one insightful comment on my scripture study
    * Hold FHE
    * Attend the Temple at least once a month
* <2016-01-07 Thu> Reading
** Matt 1: 18-25
   - v. 21 "And shall bring forth a son, and thou shalt call his name JESUS: 
     for he shall save his people from their sins."
     * It is interesting how Jesus Christ is our God. The angel says that 
       within the sentence.

*** Manual
    - Epoused means that Joesph had legal possession over Mary but not 
    physically.
    - Joseph had four dreams from God. Elder Lund said: "Four dreams from 
    God! Joseph must have been an exceptionally visionary and spiritually
    sensitive man."

** Matt 2
*** Manual 
    - "Also, the name Bethlehem (Matthew 2:6), which means “house of bread,” 
    was the place where the “Bread of Life” would be born."
    - "Regardless of who the Wise Men were or where they came from, their 
    visit shows that those who should have been aware of the signs 
    accompanying the birth of Jesus Christ failed to recognize them, while 
    righteous people from other lands, directed by the Holy Ghost, not only
    noticed the signs but acted upon them."
      * It is said to see how wicked the people were at the time. They had the
	Messiah there but they were expecting something more grandeur. Even 
	then they may have not have believed that He was the Messiah.
    - The Lord can talk to us in our dreams. We will be able to differentiate
      between a dream and revelation. The Prophet Woodruff said that we need
      to pay attention to them.
    - Jesus was taught by the Father. Therefore He did not need to be taught 
      by men. Jesus Christ was able to gain all His revelation from the 
      Father.

** Questions
   - Why does 7 signify perfection and completeness?
* <2016-01-12 Tue> Reading
** John 1: 18-34
   - v. 33, "...but he that sent me to baptize with water, the same said unto 
     me, Upon whom thou shalt see the Spirit descending, and remaining on him,
     the same is he which baptizeth with the Holy Ghost."

** Matt 3
   - v. 11, "...he shall baptize you with the Holy Ghost, and with fire:"

** Luke 3:21-23
   - v. 22, "...Thou art my beloved Son; in thee I am well pleased."

** Matt 4: 1-17
   - v. 11, "Then the devil leaveth him, and, behold, angels came and 
     ministered unto him."

** Luke 4:1-32
   - v. 24, "No prophet is accepted in his own country."
