
#+TITLE Notes -*- mode: org -*-
#+DATE 10/3/2015

* General Conference 10/3/2015-10/4/15
** 1st Session
*** President Utchdorf
    - Sometimes us as people can't trust the simple and
      small truths. We want to have something that is more
      complicated.
    - A child can grasp of the Gospel of Jesus Christ.
    - Suggestions 
      1. Simplfy your approach to your disciplship
      2. Start where you are

*** Elder Ballard
    - If we accepts Christ's disciples then we are
      accepting Christ and His Church.
    - 

*** Elder Maynes
    - If we live Christ center lives we can truly live
      the life that has all happiness within it.

*** Sister Marriott
    - When we open our hearts to the Spirit we are willing
      to let us learn what we need that Heavenly Father
      wants to give us.

*** Elder Lawrence
    - The Holy Ghost will tells us honestly of what we
      need to improve on. The Holy Ghost will not be afraid
      to tell us.
    - The Holy Ghost is the best companion.
    - The Scrament is the perfect to time to ask "What lack
      I yet?"
    - We can lay the foundation.

*** Elder Vinas

*** Elder Cook
    - Honoring the Sabbath can helps us to come closer to 
      the Savior.
    - IT is a sign of our devotion to Heavenly Father
    - Divine protection is given to us when we are 
      rightous.
** 2nd Session
*** Elder Hales
    - One of the best things that you can do is to avoid
      the temptation.
    - Knowledge does away with darkness
    - With knowledge there is power.

*** Elder Holland
    - Mother, is a very sacred and highest honor that the
      Lord has given to her.
    - Maternal love has to be divine.
    - You are doing better then you think you are.
    - Your love never faileth.

*** Elder Foster
    - Understanding and hearing are to seperate things.
    - It is never too early and never too late to begin
      teaching your children. 
    - I know what your next (situation, trial) is, I have 
      been there before, I know what you will go through,
      I will be here for you to help you through that.

*** Elder Montoya

*** Elder Stanfill
** Priesthood Session
*** Elder Anderson
    - Your faith will either grow and become stronger or
      it will start to wilt and die.
    - Faith comes by choice.

*** Elder Bennett

*** President Utchdorf
    - Do we stand loyal to God?
    - Does are actions show what we claim to believe in?
    - Do we talk the talk or walk the walk?
    - Do we help the sick, the poor, and the werry?
    - Have courage to believe.

*** President Eyring
    - 

*** President Monson
** 3rd Session
*** President Monson

*** Elder Rasband
    - Love one another as I have loved you.

*** Elder Stevenson
    - Do not focus on the things that you can't do but to focus
      on the things that you can do.

*** Elder Renlund
    - The Lord has called you so that He can do His work through 
      Him. But you have to let Him do it. It is about Him and His
      work.

*** President Nelson
    - I need my wife.
    - Woman have a unique perspective. Their strength, spirit, and
      inspiration will help us to become better and to grow 
      Christ's church.

*** Elder Schwitzer

*** Elder Costa

*** President Eyring
    - Whatever the Spirit says to you, do it.
    - As you keep on doing the promptings you will then recieve more
      and more from the Spirit.


** 4th Session
*** Elder Christofferson
    - As a church we can provide more help to people.
    - With the church made it possible to carry the work that
      the Lord wants to accomplish on the earth.

*** President Durrant Sunady School President
    - Ponder the scriptures.
    - Find ways that you can ponder the scriptures.
    - Dicipline yourself and do it.

*** Elder Keetch
    - Don't be too critical about the barrier. It is the only 
      thing that is keeping you from being devoured.
    - We become what He desires us to become.

*** Sister Stephens
    - "If ye love me keep my commandments" :: John 14:15
    - Trust God.
    - Trust the whisperings of the Spirit.

*** Elder Haynie

*** Elder Clark

*** Elder Bednar
* 10/11/2015 Romans 9-12
** Principles and Doctrines
   1. "For with the heart man believeth unto righteousness; and with the mouth confession is 
      made unto salvation." Romans 10:10
   2. "So we, being many, are one body in Christ, and every one members one of another." Romans 12:5
   3. "Be not overcome of evil, but overcome evil with good." Romans 12:21

* 10/14/2015 1 Corinthians 1-16
  1. "But as it is written, Eye hath not seen, nor ear heard, neither have entered into the 
     heart of man, the things which God hath prepared for them that love him." Chap. 2:9
  2. "What? know ye not that your body is the temple of the Holy Ghost which
     is in you, which ye have of God, and ye are not your own?" 1 Cor. 6:19
  3. "But I would have you know, that the head of every man is Christ; and the
     head of the woman is the man; and the head of Christ is God." 1 Cor. 11:3
  4. "Nevertheless neither is the man without the woman, neither the woman
     without the man, in the Lord." 1 Cor. 11:11
  5. "And now abideth faith, hope, charity, these three; but the greatest of
     these is charity." 1 Cor. 13:13

* <2015-10-18 Sun> 2 Corinthians
** Doctrines, Principles
   1. "But we all, with open face beholding as in a glass the glory of the Lord, are 
      changed into the same image from glory to glory, even as by the Spirit of the 
      Lord." Chap 3:18
   2. "For God, who commanded the light to shine out of darkness. hath shined in our 
      hearts, to give the light of the knowledge of the glory of God in the face of 
      Jesus Christ" Chap 4:6
      
* <2015-10-19 Mon> 2 Corinthians
** Principles, Doctrines
   1. "But this I say, He which soweth sparinly shall reap also sparingly; and he
      which soweth bountifully shall reap also bountifully." Chap. 9:6

** Pondering about the Gospel in my life
   Things that I/we need to do
   1. Go to the Temple :: Do initatory
   2. Do Family History/Indexing
   3. Prepare lessons better
   4. Pray night and day
   5. Read scriptures with the Spirit

* <2015-10-21 Wed> Galatians - Ephesians
** Principles, Doctrines
*** Galatians
   1. "Christ hath redeemed us from the curse of the law, being made a curse for 
      us: for it is written, Cursed is every one that hangeth on a tree:" Chap 3:13
   2. "This I say then, Walk in the Spirit, and ye shall not fulfil the lust of the 
      flesh."
      
      "For the flesh lusteth against the Spirit, and the Spirit against the flesh: 
       and these are contrary the one to the other: so that ye cannot do the things 
       that ye would." Chap 5: 16-17

*** Ephesians
   1. "One Lord, one faith, one baptism,"

      "One God and Father of all, who is above all, and through all, and in you 
      all." Chap. 4:5-6

* <2015-10-25 Sun> Philippians
** Doctrines and principles
   1. "Finally, brethren, whatsoever things are true, whatsoever things are 
      honest, whatsoever things are just, whatsoever things are pure, 
      whatsoever things are lovely, whatsoever things are of good report; 
      if there be any virtue, and if there be any praise, think on these 
      things." Chap 4:8

* <2015-10-26 Mon> Colossians
** Doctrines and principles
   1. Chap 3: 1-4 
      i.   If ye then be risen with Christ, seek those things which are above, 
           where Christ sitteth on the right hand of God.
      ii.  Set your affection on things above, not on things on the earth.
      iii. For ye are dead, and your life is hid with Christ in God.
      iv.  When Christ, who is our life, shall appear, then shall ye also 
           appear with him in glory.If ye then be risen with Christ, seek 
           those things which are above, where Christ sitteth on the right 
           hand of God.
   2. And above all these things put on charity, which is the bond of 
      perfectness. Chap 3:14

* <2015-10-27 Tue> 1 Thessalonians - 2 Thessalonians
** Doctrines and principles
   1. "For our gospel cam not unto you in word only, but also in power, and
      in the Holy Ghost, and in much assurance; as ye know what manner of men 
      we were among you for your sake." Chap 1:5
   2. Chap 3:11-13
      i.   "Now God himself and our Father, and our Lord Jesus Christ, direct 
           our way unto you."
      ii.  "And the Lord make you to increase and abound in love one toward
           another, and toward all men, even as we do toward you:"
      iii. "To the end he my stablish your hearts unblameable in holiness 
           before God, even our Father, at the coming of our Lord Jesus 
           Christ with all his saints."
   3. "For God hath not called us unto uncleaness, but unto holiness." 
      Chap 4:7

* <2015-11-01 Sun> 1 Timothy, 2 Timothy, Titus, Philemon
** 1 Timothy   
   1. Chap 1:5
      i. "Now the end of the commandment is charity out of a pure heart, and of a good conscience, and of faith 
         unfeigned:"
   2. "Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in 
      charity, in spirit, in faith, in purity." Chap. 4:12
   3. "Fight the good fight of faith, lay hold on eternal life, whereunto thou art also called, and hast 
      professed a good profession before many witnesses." Chap. 6:12

** 2 Timothy
   1. "Thou therefore endure hardness, as a good soldier of Jesus Christ." Chp. 2:3
   2. Chap 4:6-8
      i.   For I am now ready to be offered, and the time of my departure is at hand.
      ii.  I have fought a good fight, I have finished my course, I have kept the faith:
      iii. Henceforth there is laid up for me a crown of righteousness, which the Lord, the righteous judge, 
           shall give me at that day: and not to me only, but unto all them also that love his appearing.

** Titus
   1. "For the grace of God that bringeth salvation hath appeared to all men," Chap. 2:11

* <2015-11-04 Wed> Hebrews 1-6
  1. "Therefore we ought to give the more earnest heed to the things which we have heard, lest at any time we 
     should let them slip." Chap. 2:1
  2. "So we see that they could not enter in because of unbelief." Chap. 3:19
  3. "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the 
     dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts 
     and intents of the heart." Chap. 4:12
  4. "For God is not unrighteous to forget your work and labour of love, which ye have shewed toward his name, 
     in that ye have ministered to the saints, and do minister." Chap. 6:10


